#!/usr/bin/perl

use warnings;
use strict;
use Encode;

require 'plugins/rpc.pl';

sub import {
	rpc_call("hook", type => "htmlize", id => "nbl", call => "htmlize");
}

sub htmlize (@) {
	my %params=@_;
	my $content = decode_utf8(encode_utf8($params{content}));

	eval q{use Text::Nimble};
	return $content if $@;
	return Text::Nimble::render(html => $content);
}
